import ExploreIcon from "@mui/icons-material/Explore";
import GroupIcon from "@mui/icons-material/Group";
import OndemandVideoSharpIcon from "@mui/icons-material/OndemandVideoSharp";
import BusinessCenterIcon from "@mui/icons-material/BusinessCenter";
import ArrowForwardIosRoundedIcon from "@mui/icons-material/ArrowForwardIosRounded";
import Image from "next/image";
import React from "react";
import HeaderLink from "../components/HeaderLink";
import Head from "next/head";
import { getProviders, signIn } from "next-auth/react";

function Home({ providers }) {
  return (
    <div className="relative space-y-10">
      <Head>
        <title>LinkedIn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex items-center justify-around py-4">
        {/* Logo */}
        <div className="relative h-10 w-36">
          <Image
            src="/img/logo.svg"
            objectFit="contain"
            layout="fill"
            alt="logo"
          />
        </div>
        {/* Menu List */}
        <div className="flex items-center divide-gray-300 sm:divide-x">
          <ul className="hidden pr-4 space-x-8 sm:flex">
            <HeaderLink Icon={ExploreIcon} text="Discover" />
            <HeaderLink Icon={GroupIcon} text="People" />
            <HeaderLink Icon={OndemandVideoSharpIcon} text="Learning" />
            <HeaderLink Icon={BusinessCenterIcon} text="Jobs" />
          </ul>
          {/* Object.value digunakan untuk mengubah object menjadi array, dan hal ini digunakan hanya jika menggunakan multiple provider */}
          {Object.values(providers)?.map((provider) => (
            <div key={provider.name}>
              <div className="pl-4">
                <button
                  onClick={() => signIn(provider.id, { callbackUrl: "/" })}
                  className="text-blue-700 font-semibold rounded-full px-5 py-1.5 border border-blue-700 hover:border-2"
                >
                  Sign In
                </button>
              </div>
            </div>
          ))}
        </div>
      </header>

      <main className="flex flex-col items-center max-w-screen-lg mx-auto xl:flex-row">
        {/* Item Left */}
        <div className="space-y-6 xl:space-y-10">
          <h1 className="text-3xl md:text-5xl text-amber-800/80 !leading-snug max-w-xl pl-4 xl:pl-0">
            Welcome to your professional community
          </h1>
          <div className="space-y-4">
            <div className="intent">
              <h2 className="text-xl">Search for a job</h2>
              <ArrowForwardIosRoundedIcon className="text-gray-700" />
            </div>
            <div className="intent">
              <h2 className="text-xl">Find a person you know</h2>
              <ArrowForwardIosRoundedIcon className="text-gray-700" />
            </div>
            <div className="intent">
              <h2 className="text-xl">Learn a new skill</h2>
              <ArrowForwardIosRoundedIcon className="text-gray-700" />
            </div>
          </div>
        </div>
        {/* Item right */}
        <div className="relative xl:absolute w-80 h-80 top-10 right-1 xl:w-[650px] xl:h-[650px]">
          <Image src="/img/home-picture.svg" layout="fill" priority alt="" />
        </div>
      </main>
    </div>
  );
}

export default Home;

export async function getServerSideProps() {
  const providers = await getProviders();

  return {
    props: {
      providers,
    },
  };
}
